[tool.pytest.ini_options]
markers = [
    "skipif_missing_gsl: skip test if NEST was built without GSL support",
    "skipif_missing_mpi: skip test if NEST was built without MPI support",
    "skipif_missing_threading: skip test if NEST was built without multithreading support"
]
